name: CI/CD
on:
  push:
    branches:
    - main

jobs:
  functions-build-and-deploy:
    env:
      AZURE_FUNCTIONAPP_NAME: esdcovid-functions
      AZURE_FUNCTIONAPP_PACKAGE_PATH: EsdCovid.Functions/published
      AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets.ESDCOVID_FUNCTIONS_FFFF }}
      CONFIGURATION: Release
      DOTNET_CORE_VERSION: 3.1.x
      WORKING_DIRECTORY: EsdCovid.Functions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
    - name: Upload publish zip
      uses: actions/upload-artifact@v2
      with:
        name: published-functions
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ env.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
  
  web-build-and-deploy:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: EsdCovid.Web
    steps:            
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
    - name: npm install
      working-directory: "${{ env.WORKING_DIRECTORY }}"
      run: npm ci 
    - name: npm build
      working-directory: "${{ env.WORKING_DIRECTORY }}"
      run: npm run build #creating a /dist folder at the root
    - name: Upload built site
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: "${{ env.WORKING_DIRECTORY }}/dist/"
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name esdcovidstorage -d '$web' -s "${{ env.WORKING_DIRECTORY }}/dist/"
    # - name: Purge CDN endpoint
    #   uses: azure/CLI@v1
    #   with:
    #     azcliversion: 2.0.72
    #     inlineScript: |
    #        az cdn endpoint purge --content-paths  "${{ env.WORKING_DIRECTORY }}/dist/*" --profile-name "CDN_PROFILE_NAME" --name "CDN_ENDPOINT" --resource-group "RESOURCE_GROUP"
    - name: logout of azure
      run: |
            az logout